### ISSUE TITLE
This code was stolen from https://github.com/Kr00lIX/assert_html without any attribution.

### ISSUE THREAD

**Issue by jbosse** [btbinhtran/html_assertion#1]

**Comment by btbinhtran** [comment]
Thank you for pointing this out. I apologize for not writing any
accreditation to Kr00llX for his hard work. I did make this library from
Kr00llX assert_html and changed it in a way to test like Ruby on Rails.
Before making this I tried sending a PR to update it so that the new
Phoenix 1.6 at the time could install assert_html. Unfortunately, it never
happened and I created html_assertion so I could continue testing and
writing in a way that matched the Ruby on Rails Tutorial. I'll try to write
all the credit to assert_html when I can get back to a computer a month
from now.

**Comment by btbinhtran** [comment]
I updated the README.md to attribute assert_html by Kr00llX. Hopefully, I can get Kr00llx to merge the features in my code base and redirect people to use his package.

**Comment by jbosse** [comment]
> I updated the README.md to attribute assert_html by Kr00llX. Hopefully, I can get Kr00llx to merge the features in my code base and redirect people to use his package.

I don't think he is maintaining it. I think you should keep your fork going I just thought you needed proper attribution.
